name: CI Node App

on:
  pull_request:
    types: 
      - synchronize
      - opened

jobs:
  Build-App:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 15
      uses: actions/setup-node@v4
      with:
        node-version: 15
        cache: 'npm'
    - name: Install
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test
      env:
        CI: true
    - name: Build
      run: npm run build